# Generated by Django 3.2.5 on 2021-08-07 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
