# Generated by Django 3.2.5 on 2021-08-09 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_boschairinstitutemapping_dept_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boschairinstitutemapping',
            name='dept_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.departmentinstitutecodes'),
        ),
    ]
