# Generated by Django 3.2.4 on 2022-06-20 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_emailstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=0)),
                ('full_name', models.TextField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'user_courses',
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('code', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'u_department',
            },
        ),
        migrations.CreateModel(
            name='Institutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=0)),
                ('institution_code', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'u_institutions',
            },
        ),
        migrations.AlterModelTable(
            name='campus',
            table='u_campus',
        ),
        migrations.AlterModelTable(
            name='departmentinstitutecodes',
            table='u_department_institute_code',
        ),
        migrations.CreateModel(
            name='CampusInstitutionMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.campus')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.institutions')),
            ],
            options={
                'db_table': 'u_campus_institution_mapping',
            },
        ),
        migrations.CreateModel(
            name='CampusInstitutionCourseMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.campus')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.course')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.institutions')),
            ],
            options={
                'db_table': 'u_campus_institution_course_mapping',
            },
        ),
        migrations.CreateModel(
            name='CampusInstitutionCourseDepartmentMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.campus')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.departments')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.institutions')),
            ],
            options={
                'db_table': 'u_campus_institution_course_department_mapping',
            },
        ),
    ]
