# Generated by Django 3.2.4 on 2022-06-21 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_auto_20220620_1723'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='u_courses',
        ),
    ]
