# Generated by Django 3.2.4 on 2022-06-21 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0008_alter_course_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='UCourse',
        ),
    ]
