# Generated by Django 3.2.4 on 2022-06-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0009_rename_course_ucourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='campus_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
