# Generated by Django 3.2.4 on 2022-06-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0010_campus_campus_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentinstitutecodes',
            name='name',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
