# Generated by Django 3.2.4 on 2022-06-21 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0012_departmentinstitutecodes_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campusinstitutioncoursedepartmentmapping',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.departmentinstitutecodes'),
        ),
    ]
