# Generated by Django 3.2.5 on 2021-07-31 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0001_initial'),
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        #('auth', '0013_group_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.TextField(null=True)),
                ('desc1', models.TextField(null=True)),
                ('instruction_plan', models.FileField(upload_to='media/course/')),
                ('instruction_plan_practical', models.FileField(null=True, upload_to='media/course/')),
                ('active_step', models.IntegerField(null=True)),
                ('version', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('version_status', models.BooleanField(default=0)),
                ('total_no_of_contact_hours', models.TextField(null=True)),
                ('L', models.TextField(null=True)),
                ('T', models.TextField(null=True)),
                ('P', models.TextField(null=True)),
                ('S', models.TextField(null=True)),
                ('J', models.TextField(null=True)),
                ('C', models.TextField(null=True)),
                ('pre_requisites', models.TextField(null=True)),
                ('alternative_exposure', models.TextField(null=True)),
                ('course_descrption', models.TextField(null=True)),
                ('specific_instruction_objectives', models.TextField(null=True)),
                ('co_requisite1', models.TextField(null=True)),
                ('co_requisite2', models.TextField(null=True)),
                ('co_requisite3', models.TextField(null=True)),
                ('co_requisite4', models.TextField(null=True)),
                ('co_requisite5', models.TextField(null=True)),
                ('pre_requisites_yes1', models.TextField(null=True)),
                ('pre_requisites_yes2', models.TextField(null=True)),
                ('pre_requisites_yes3', models.TextField(null=True)),
                ('pre_requisites_yes4', models.TextField(null=True)),
                ('pre_requisites_yes5', models.TextField(null=True)),
                ('course_code', models.CharField(max_length=10, null=True)),
                ('practical_referance', models.JSONField(null=True)),
                ('practical_topic_mapping', models.JSONField(null=True)),
                ('project_topic', models.JSONField(null=True)),
                ('online_resources', models.JSONField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=70)),
                ('code', models.CharField(max_length=20)),
                ('status', models.IntegerField(default=1)),
                ('short_code', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'course_course_category',
            },
        ),
        migrations.CreateModel(
            name='CourseHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=1)),
                ('program_status', models.BooleanField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.programs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_user_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_course_header',
            },
        ),
        migrations.CreateModel(
            name='CourseStatusLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'course_status_levels',
            },
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('code', models.CharField(max_length=20)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'course_course_type',
            },
        ),
        migrations.CreateModel(
            name='LevelOfCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'course_level_of_course',
            },
        ),
        migrations.CreateModel(
            name='PedagogyTools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'course_pedagogy_tools',
            },
        ),
        migrations.CreateModel(
            name='SyllabusType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'course_syllabus_type',
            },
        ),
        migrations.CreateModel(
            name='Websites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_website', models.TextField()),
                ('last_accessed', models.DateTimeField(auto_now_add=True)),
                ('website_url', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('unit_mapping', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_websites',
            },
        ),
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('author', models.TextField(null=True)),
                ('publisher', models.TextField(null=True)),
                ('place_of_publication', models.TextField(null=True)),
                ('year', models.IntegerField(null=True)),
                ('edition', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('isbn', models.TextField(null=True)),
                ('unit_mapping', models.TextField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_reference',
            },
        ),
        migrations.CreateModel(
            name='ProgramSpecificOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pso', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_program_specific_outcome',
            },
        ),
        migrations.CreateModel(
            name='JournalBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('author', models.TextField()),
                ('year', models.TextField()),
                ('doi_url', models.TextField()),
                ('pages', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('unit_mapping', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_journal_books',
            },
        ),
        migrations.CreateModel(
            name='CourseUserMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_edit', models.IntegerField(null=True)),
                ('comment', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=1, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.course')),
                ('course_header', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course_management.courseheader')),
                ('course_status_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_status_level', to='course_management.coursestatuslevels')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('to_user_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cour_to_user_group', to='auth.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_created_user_id', to=settings.AUTH_USER_MODEL)),
                ('user_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'db_table': 'course_user_mapping',
            },
        ),
        migrations.CreateModel(
            name='CourseUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_no', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.course')),
            ],
            options={
                'db_table': 'course_units',
            },
        ),
        migrations.CreateModel(
            name='CourseSyllabusPractical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField()),
                ('version', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.course')),
                ('syllabus_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.syllabustype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_syllabus_practical',
            },
        ),
        migrations.CreateModel(
            name='CourseSyllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.TextField()),
                ('short_title', models.CharField(max_length=500)),
                ('number_of_contact_hours', models.IntegerField()),
                ('version', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('outcome_1', models.TextField(null=True)),
                ('level_1', models.TextField(null=True)),
                ('outcome_2', models.TextField(null=True)),
                ('level_2', models.TextField(null=True)),
                ('outcome_3', models.TextField(null=True)),
                ('level_3', models.TextField(null=True)),
                ('outcome_4', models.TextField(null=True)),
                ('level_4', models.TextField(null=True)),
                ('outcome_5', models.TextField(null=True)),
                ('level_5', models.TextField(null=True)),
                ('pedagogy_tools', models.JSONField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.course')),
                ('course_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.courseunits')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_syllabus',
            },
        ),
        migrations.CreateModel(
            name='CourseOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_outcome', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_outcome',
            },
        ),
        migrations.CreateModel(
            name='CourseInstituteMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_institute_mapping',
            },
        ),
        migrations.CreateModel(
            name='CourseDepartmentMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_department_mapping',
            },
        ),
        migrations.CreateModel(
            name='CourseCoPoPso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co', models.IntegerField()),
                ('po1', models.IntegerField(null=True)),
                ('po2', models.IntegerField(null=True)),
                ('po3', models.IntegerField(null=True)),
                ('po4', models.IntegerField(null=True)),
                ('po5', models.IntegerField(null=True)),
                ('po6', models.IntegerField(null=True)),
                ('po7', models.IntegerField(null=True)),
                ('po8', models.IntegerField(null=True)),
                ('po9', models.IntegerField(null=True)),
                ('po10', models.IntegerField(null=True)),
                ('po11', models.IntegerField(null=True)),
                ('po12', models.IntegerField(null=True)),
                ('pso1', models.IntegerField(null=True)),
                ('pso2', models.IntegerField(null=True)),
                ('pso3', models.IntegerField(null=True)),
                ('pso4', models.IntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_co_po_pso',
            },
        ),
        migrations.CreateModel(
            name='CourseCampusMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.campus')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_campus_mapping',
            },
        ),
        migrations.CreateModel(
            name='CourseBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('author', models.TextField(null=True)),
                ('publisher', models.TextField(null=True)),
                ('place_of_publication', models.TextField(null=True)),
                ('year', models.IntegerField(null=True)),
                ('edition', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('isbn', models.TextField(null=True)),
                ('unit_mapping', models.TextField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_books',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='course_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.coursecategory'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_header',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course_management.courseheader'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.coursetype'),
        ),
        migrations.AddField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='dept_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.departmentinstitutecodes'),
        ),
        migrations.AddField(
            model_name='course',
            name='level_of_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.levelofcourse'),
        ),
        migrations.AddField(
            model_name='course',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.programs'),
        ),
    ]
