# Generated by Django 3.2.5 on 2021-08-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0003_alter_course_level_of_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesyllabus',
            name='number_of_contact_hours',
            field=models.CharField(max_length=3),
        ),
    ]
