# Generated by Django 3.2.5 on 2021-09-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0005_alter_coursesyllabus_number_of_contact_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
