# Generated by Django 3.2.4 on 2022-02-07 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
        ('course_management', '0007_auto_20210922_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='program_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.programtype'),
        ),
    ]
