# Generated by Django 3.2.4 on 2022-02-07 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
        ('course_management', '0008_course_program_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course_management.coursecategory'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level_of_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.programlevel'),
        ),
    ]
