# Generated by Django 3.2.4 on 2022-03-02 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_management', '0011_programcoursemapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePrerequestiesMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prerequesti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_prerequesting_mapping', to='course_management.course')),
            ],
            options={
                'db_table': 'course_prerequesties_mapping',
            },
        ),
    ]
