# Generated by Django 3.2.4 on 2022-03-03 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0014_programcategorycountmapping'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='programcategorycountmapping',
            table='program_category_count_mapping',
        ),
    ]
