# Generated by Django 3.2.4 on 2022-03-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0018_programcoursecopomapping_programcoursecopsomapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='programcoursecopomapping',
            name='po_points',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='programcoursecopsomapping',
            name='pso_points',
            field=models.IntegerField(null=True),
        ),
    ]
