# Generated by Django 3.2.4 on 2022-04-12 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_management', '0022_auto_20220324_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='co_requisites',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='course',
            name='pass_fail',
            field=models.BooleanField(default=0),
        ),
        migrations.CreateModel(
            name='CourseCorequestiesMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('corequesti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_corequesting_mapping', to='course_management.course')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_corequesties_mapping',
            },
        ),
    ]
