# Generated by Django 3.2.4 on 2022-04-13 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0023_auto_20220412_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='choice_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course_management.coursecategory'),
        ),
    ]
