# Generated by Django 3.2.4 on 2022-04-18 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0025_programcategorycountmapping_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programcategorycountmapping',
            name='label',
        ),
        migrations.AddField(
            model_name='programcategorycountmapping',
            name='label_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_label', to='course_management.coursecategory'),
        ),
    ]
