# Generated by Django 3.2.4 on 2022-05-31 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0028_alter_basket_credit_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAdmittedBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'course_admitted_batch',
            },
        ),
        migrations.CreateModel(
            name='CourseDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'course_degree',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='admitted_batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course_management.courseadmittedbatch'),
        ),
        migrations.AddField(
            model_name='course',
            name='degree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course_management.coursedegree'),
        ),
    ]
