# Generated by Django 3.2.4 on 2022-06-17 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_alter_programs_program_category'),
        ('course_management', '0029_auto_20220531_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='C',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='J',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='L',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='P',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='S',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='T',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='course_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course_management.coursetype'),
        ),
        migrations.AddField(
            model_name='basket',
            name='level_of_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.programlevel'),
        ),
        migrations.AlterModelTable(
            name='basket',
            table='course_basket',
        ),
    ]
