# Generated by Django 3.2.4 on 2022-06-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0030_auto_20220617_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='course_count',
            field=models.IntegerField(null=True),
        ),
    ]
