# Generated by Django 3.2.4 on 2022-06-21 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0013_alter_campusinstitutioncoursedepartmentmapping_department'),
        ('course_management', '0031_alter_basket_course_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedepartmentmapping',
            name='c_i_c_d',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.campusinstitutioncoursedepartmentmapping'),
        ),
    ]
