# Generated by Django 3.2.4 on 2022-06-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0033_courseobjectives'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='sdg',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='sdg_description',
            field=models.TextField(null=True),
        ),
    ]
