# Generated by Django 3.2.4 on 2022-06-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0035_alter_course_sdg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='online_resources',
            new_name='course_objectives',
        ),
        migrations.AddField(
            model_name='course',
            name='course_outcome',
            field=models.JSONField(null=True),
        ),
        migrations.DeleteModel(
            name='CourseObjectives',
        ),
    ]
