# Generated by Django 3.2.4 on 2022-06-24 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0036_auto_20220622_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20)),
                ('status', models.IntegerField(default=1)),
                ('course_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course_management.coursetype')),
            ],
            options={
                'db_table': 'course_levels',
            },
        ),
        migrations.DeleteModel(
            name='LevelOfCourse',
        ),
    ]
