# Generated by Django 3.2.4 on 2022-06-24 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0037_auto_20220624_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courselevels',
            name='course_type_id',
        ),
    ]
