# Generated by Django 3.2.4 on 2022-06-25 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0041_course_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primarybasketsubbasketmapping',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='primarybasketsubbasketmapping',
            name='primary_basket',
        ),
        migrations.RemoveField(
            model_name='primarybasketsubbasketmapping',
            name='sub_basket',
        ),
        migrations.RemoveField(
            model_name='programcoursemapping',
            name='basket',
        ),
        migrations.RemoveField(
            model_name='programcoursemapping',
            name='course',
        ),
        migrations.RemoveField(
            model_name='programcoursemapping',
            name='course_category',
        ),
        migrations.RemoveField(
            model_name='programcoursemapping',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='programcoursemapping',
            name='program',
        ),
        migrations.DeleteModel(
            name='Basket',
        ),
        migrations.DeleteModel(
            name='PrimaryBasketSubBasketMapping',
        ),
        migrations.DeleteModel(
            name='ProgramCourseMapping',
        ),
    ]
