# Generated by Django 3.2.4 on 2022-06-25 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0042_auto_20220625_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programcategorycountmapping',
            name='category',
        ),
        migrations.RemoveField(
            model_name='programcategorycountmapping',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='programcategorycountmapping',
            name='label_category',
        ),
        migrations.RemoveField(
            model_name='programcategorycountmapping',
            name='program',
        ),
        migrations.RemoveField(
            model_name='programcoursecopomapping',
            name='co',
        ),
        migrations.RemoveField(
            model_name='programcoursecopomapping',
            name='course',
        ),
        migrations.RemoveField(
            model_name='programcoursecopomapping',
            name='po',
        ),
        migrations.RemoveField(
            model_name='programcoursecopomapping',
            name='program',
        ),
        migrations.RemoveField(
            model_name='programcoursecopomapping',
            name='user',
        ),
        migrations.RemoveField(
            model_name='programcoursecopsomapping',
            name='co',
        ),
        migrations.RemoveField(
            model_name='programcoursecopsomapping',
            name='course',
        ),
        migrations.RemoveField(
            model_name='programcoursecopsomapping',
            name='program',
        ),
        migrations.RemoveField(
            model_name='programcoursecopsomapping',
            name='pso',
        ),
        migrations.RemoveField(
            model_name='programcoursecopsomapping',
            name='user',
        ),
        migrations.RemoveField(
            model_name='programcourseoutcome',
            name='course',
        ),
        migrations.RemoveField(
            model_name='programcourseoutcome',
            name='program',
        ),
        migrations.RemoveField(
            model_name='programcourseoutcome',
            name='user',
        ),
        migrations.RemoveField(
            model_name='programspecificoutcome',
            name='course',
        ),
        migrations.RemoveField(
            model_name='programspecificoutcome',
            name='program',
        ),
        migrations.RemoveField(
            model_name='programspecificoutcome',
            name='user',
        ),
        migrations.DeleteModel(
            name='MinorCoreProgramMapping',
        ),
        migrations.DeleteModel(
            name='ProgramCategoryCountMapping',
        ),
        migrations.DeleteModel(
            name='ProgramCourseCOPOMapping',
        ),
        migrations.DeleteModel(
            name='ProgramCourseCOPSOMapping',
        ),
        migrations.DeleteModel(
            name='ProgramCourseOutcome',
        ),
        migrations.DeleteModel(
            name='ProgramSpecificOutcome',
        ),
    ]
