# Generated by Django 3.2.4 on 2022-06-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0043_auto_20220625_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='priority',
            field=models.IntegerField(null=True),
        ),
    ]
