# Generated by Django 3.2.4 on 2022-02-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programtype',
            name='code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
