# Generated by Django 3.2.4 on 2022-03-19 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_alter_programusermapping_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'program_category',
            },
        ),
        migrations.AddField(
            model_name='programs',
            name='program_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.programcategory'),
        ),
    ]
