# Generated by Django 3.2.4 on 2022-03-19 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_auto_20220319_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programs',
            name='program_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='programs.programcategory'),
        ),
    ]
