# Generated by Django 3.2.4 on 2022-06-25 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0043_auto_20220625_1804'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programs', '0006_alter_programs_program_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramCourseBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket_name', models.TextField()),
                ('course_count', models.IntegerField(null=True)),
                ('credit_count', models.IntegerField(null=True)),
                ('choice_count', models.IntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('L', models.TextField(null=True)),
                ('T', models.TextField(null=True)),
                ('P', models.TextField(null=True)),
                ('S', models.TextField(null=True)),
                ('J', models.TextField(null=True)),
                ('C', models.TextField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course_management.coursecategory')),
                ('course_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course_management.coursetype')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_basket_created_by', to=settings.AUTH_USER_MODEL)),
                ('level_of_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.programlevel')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.programs')),
            ],
            options={
                'db_table': 'program_course_basket',
            },
        ),
        migrations.CreateModel(
            name='ProgramSpecificOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pso', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.course')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.programs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'program_specific_outcome',
            },
        ),
        migrations.CreateModel(
            name='ProgramCourseOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.course')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.programs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'program_course_outcome',
            },
        ),
        migrations.CreateModel(
            name='ProgramCourseMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('item_type', models.IntegerField(default=0)),
                ('basket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.programcoursebasket')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.course')),
                ('course_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course_management.coursecategory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.programs')),
            ],
            options={
                'db_table': 'program_course_mapping',
            },
        ),
        migrations.CreateModel(
            name='ProgramCourseCOPSOMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pso_points', models.IntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('co', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.courseoutcome')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.course')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.programs')),
                ('pso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.programspecificoutcome')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'program_course_co_pso_mapping',
            },
        ),
        migrations.CreateModel(
            name='ProgramCourseCOPOMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_points', models.IntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('co', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.courseoutcome')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.course')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.programcourseoutcome')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.programs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'program_course_co_po_mapping',
            },
        ),
        migrations.CreateModel(
            name='ProgramCategoryCountMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course_management.coursecategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_course_category_created_by', to=settings.AUTH_USER_MODEL)),
                ('label_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_label', to='course_management.coursecategory')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.programs')),
            ],
            options={
                'db_table': 'program_category_count_mapping',
            },
        ),
        migrations.CreateModel(
            name='MinorCoreProgramMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.coursecategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_minor_category_created_by', to=settings.AUTH_USER_MODEL)),
                ('mapped_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minor_prog', to='programs.programs')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.programs')),
            ],
            options={
                'db_table': 'program_minor_core_program_mapping',
            },
        ),
    ]
