# Generated by Django 3.2.4 on 2022-06-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0008_auto_20220629_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='programcoursegroup',
            name='symbol',
            field=models.TextField(null=True),
        ),
    ]
