# Generated by Django 3.2.4 on 2022-06-30 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_programcoursegroup_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programcategorycountmapping',
            name='label_category',
        ),
    ]
