# Generated by Django 3.2.4 on 2022-06-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0010_remove_programcategorycountmapping_label_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='programcategorycountmapping',
            name='label_category',
            field=models.JSONField(null=True),
        ),
    ]
